# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  run_database:
    machine: true
    steps:
      - checkout

      - run: cd docker-scripts && ./run-dev-database.sh

  build:
    docker:
      # specify the version you desire here
      # - image: circleci/node:7.10
      - image: cypress/base:8
        environment:
            ## this enables colors in the output
            TERM: xterm
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-sunmait-blog-cache-{{ .Branch }}-{{ checksum "client/package-lock.json" }}
            - v1-sunmait-blog-cache-{{ .Branch }}-
            - v1-sunmait-blog-cache-

      - run: cd client && yarn
      - run: cd client && yarn start

      - save_cache:
          key: v1-sunmait-blog-cache-{{ .Branch }}-{{ checksum "client/package-lock.json" }}
          paths:
              - ~/.npm
              - ~/.cache

      - run: cd client && yarn e2e-ci