# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: 'build server container'
          command: cd docker-scripts && ./build-prod-server.sh
      - run:
          name: 'run database'
          command: cd docker-scripts && ./run-prod-database.sh
          background: true
      - run:
          name: 'seed database'
          command: cd docker-scripts && ./seed-prod-server.sh
      - run:
          name: 'run server'
          command: cd docker-scripts && ./run-prod-server.sh
          background: true
      - run: sleep 30
      # - restore_cache:
      #     keys:
      #       - v1-sunmait-blog-cache-{{ .Branch }}-{{ checksum "client/package-lock.json" }}
      #       - v1-sunmait-blog-cache-{{ .Branch }}-
      #       - v1-sunmait-blog-cache-
      - run:
          name: 'install client dependencies'
          command: cd client && yarn
      - run:
          name: 'run build client code'
          command: cd client && npm start
          background: true
      - run: sleep 30
      # - save_cache:
      #     key: v1-sunmait-blog-cache-{{ .Branch }}-{{ checksum "client/package-lock.json" }}
      #     paths:
      #         - ~/.npm
      #         - ~/.cache
  test1:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: cd client && yarn e2e-ci

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
